// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: veins_avswu.proto
#ifndef GRPC_veins_5favswu_2eproto__INCLUDED
#define GRPC_veins_5favswu_2eproto__INCLUDED

#include "veins_avswu.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace avswu {

//
// service definition
//
class Avswu final {
 public:
  static constexpr char const* service_full_name() {
    return "avswu.Avswu";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    //
    // polkadot blockchain RPCs, definitions match smart contract implementations contract in lib.rs
    //
    // write commitment
    virtual ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::avswu::AvswuBlockchainWriteCommitmentReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteCommitmentReply>> AsyncAvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteCommitmentReply>>(AsyncAvswuBlockchainWriteCommitmentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteCommitmentReply>> PrepareAsyncAvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteCommitmentReply>>(PrepareAsyncAvswuBlockchainWriteCommitmentRaw(context, request, cq));
    }
    // read commitment vector
    virtual ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadCommitmentVectorReply>> AsyncAvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadCommitmentVectorReply>>(AsyncAvswuBlockchainReadCommitmentVectorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadCommitmentVectorReply>> PrepareAsyncAvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadCommitmentVectorReply>>(PrepareAsyncAvswuBlockchainReadCommitmentVectorRaw(context, request, cq));
    }
    //
    // polkadot blockchain RPCs, definitions match smart contract implementations contract in lib.rs
    //
    // write notification
    virtual ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::avswu::AvswuBlockchainWriteNotificationReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteNotificationReply>> AsyncAvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteNotificationReply>>(AsyncAvswuBlockchainWriteNotificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteNotificationReply>> PrepareAsyncAvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteNotificationReply>>(PrepareAsyncAvswuBlockchainWriteNotificationRaw(context, request, cq));
    }
    // read notification 
    virtual ::grpc::Status AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::avswu::AvswuBlockchainReadNotificationReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadNotificationReply>> AsyncAvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadNotificationReply>>(AsyncAvswuBlockchainReadNotificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadNotificationReply>> PrepareAsyncAvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadNotificationReply>>(PrepareAsyncAvswuBlockchainReadNotificationRaw(context, request, cq));
    }
    // read last notification
    virtual ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::avswu::AvswuBlockchainReadLastNotificationReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationReply>> AsyncAvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationReply>>(AsyncAvswuBlockchainReadLastNotificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationReply>> PrepareAsyncAvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationReply>>(PrepareAsyncAvswuBlockchainReadLastNotificationRaw(context, request, cq));
    }
    // read notification list given a manufacturer list supported by the rsu
    virtual ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationListReply>> AsyncAvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationListReply>>(AsyncAvswuBlockchainReadLastNotificationListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationListReply>> PrepareAsyncAvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationListReply>>(PrepareAsyncAvswuBlockchainReadLastNotificationListRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      //
      // polkadot blockchain RPCs, definitions match smart contract implementations contract in lib.rs
      //
      // write commitment
      virtual void AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // read commitment vector
      virtual void AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      //
      // polkadot blockchain RPCs, definitions match smart contract implementations contract in lib.rs
      //
      // write notification
      virtual void AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // read notification 
      virtual void AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // read last notification
      virtual void AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // read notification list given a manufacturer list supported by the rsu
      virtual void AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteCommitmentReply>* AsyncAvswuBlockchainWriteCommitmentRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteCommitmentReply>* PrepareAsyncAvswuBlockchainWriteCommitmentRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* AsyncAvswuBlockchainReadCommitmentVectorRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* PrepareAsyncAvswuBlockchainReadCommitmentVectorRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteNotificationReply>* AsyncAvswuBlockchainWriteNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainWriteNotificationReply>* PrepareAsyncAvswuBlockchainWriteNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadNotificationReply>* AsyncAvswuBlockchainReadNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadNotificationReply>* PrepareAsyncAvswuBlockchainReadNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationReply>* AsyncAvswuBlockchainReadLastNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationReply>* PrepareAsyncAvswuBlockchainReadLastNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationListReply>* AsyncAvswuBlockchainReadLastNotificationListRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::avswu::AvswuBlockchainReadLastNotificationListReply>* PrepareAsyncAvswuBlockchainReadLastNotificationListRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::avswu::AvswuBlockchainWriteCommitmentReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>> AsyncAvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>>(AsyncAvswuBlockchainWriteCommitmentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>> PrepareAsyncAvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>>(PrepareAsyncAvswuBlockchainWriteCommitmentRaw(context, request, cq));
    }
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>> AsyncAvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>>(AsyncAvswuBlockchainReadCommitmentVectorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>> PrepareAsyncAvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>>(PrepareAsyncAvswuBlockchainReadCommitmentVectorRaw(context, request, cq));
    }
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::avswu::AvswuBlockchainWriteNotificationReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>> AsyncAvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>>(AsyncAvswuBlockchainWriteNotificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>> PrepareAsyncAvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>>(PrepareAsyncAvswuBlockchainWriteNotificationRaw(context, request, cq));
    }
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::avswu::AvswuBlockchainReadNotificationReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>> AsyncAvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>>(AsyncAvswuBlockchainReadNotificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>> PrepareAsyncAvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>>(PrepareAsyncAvswuBlockchainReadNotificationRaw(context, request, cq));
    }
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::avswu::AvswuBlockchainReadLastNotificationReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>> AsyncAvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>>(AsyncAvswuBlockchainReadLastNotificationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>> PrepareAsyncAvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>>(PrepareAsyncAvswuBlockchainReadLastNotificationRaw(context, request, cq));
    }
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>> AsyncAvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>>(AsyncAvswuBlockchainReadLastNotificationListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>> PrepareAsyncAvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>>(PrepareAsyncAvswuBlockchainReadLastNotificationListRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response, std::function<void(::grpc::Status)>) override;
      void AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response, std::function<void(::grpc::Status)>) override;
      void AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response, std::function<void(::grpc::Status)>) override;
      void AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response, std::function<void(::grpc::Status)>) override;
      void AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response, std::function<void(::grpc::Status)>) override;
      void AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response, std::function<void(::grpc::Status)>) override;
      void AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>* AsyncAvswuBlockchainWriteCommitmentRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>* PrepareAsyncAvswuBlockchainWriteCommitmentRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* AsyncAvswuBlockchainReadCommitmentVectorRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* PrepareAsyncAvswuBlockchainReadCommitmentVectorRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>* AsyncAvswuBlockchainWriteNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>* PrepareAsyncAvswuBlockchainWriteNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>* AsyncAvswuBlockchainReadNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>* PrepareAsyncAvswuBlockchainReadNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>* AsyncAvswuBlockchainReadLastNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>* PrepareAsyncAvswuBlockchainReadLastNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>* AsyncAvswuBlockchainReadLastNotificationListRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>* PrepareAsyncAvswuBlockchainReadLastNotificationListRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AvswuBlockchainWriteCommitment_;
    const ::grpc::internal::RpcMethod rpcmethod_AvswuBlockchainReadCommitmentVector_;
    const ::grpc::internal::RpcMethod rpcmethod_AvswuBlockchainWriteNotification_;
    const ::grpc::internal::RpcMethod rpcmethod_AvswuBlockchainReadNotification_;
    const ::grpc::internal::RpcMethod rpcmethod_AvswuBlockchainReadLastNotification_;
    const ::grpc::internal::RpcMethod rpcmethod_AvswuBlockchainReadLastNotificationList_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    //
    // polkadot blockchain RPCs, definitions match smart contract implementations contract in lib.rs
    //
    // write commitment
    virtual ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response);
    // read commitment vector
    virtual ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response);
    //
    // polkadot blockchain RPCs, definitions match smart contract implementations contract in lib.rs
    //
    // write notification
    virtual ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response);
    // read notification 
    virtual ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response);
    // read last notification
    virtual ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response);
    // read notification list given a manufacturer list supported by the rsu
    virtual ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AvswuBlockchainWriteCommitment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AvswuBlockchainWriteCommitment() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AvswuBlockchainWriteCommitment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainWriteCommitment(::grpc::ServerContext* context, ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::grpc::ServerAsyncResponseWriter< ::avswu::AvswuBlockchainWriteCommitmentReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AvswuBlockchainReadCommitmentVector : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AvswuBlockchainReadCommitmentVector() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AvswuBlockchainReadCommitmentVector() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadCommitmentVector(::grpc::ServerContext* context, ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::grpc::ServerAsyncResponseWriter< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AvswuBlockchainWriteNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AvswuBlockchainWriteNotification() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AvswuBlockchainWriteNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainWriteNotification(::grpc::ServerContext* context, ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::grpc::ServerAsyncResponseWriter< ::avswu::AvswuBlockchainWriteNotificationReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AvswuBlockchainReadNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AvswuBlockchainReadNotification() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_AvswuBlockchainReadNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadNotification(::grpc::ServerContext* context, ::avswu::AvswuBlockchainReadNotificationRequest* request, ::grpc::ServerAsyncResponseWriter< ::avswu::AvswuBlockchainReadNotificationReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AvswuBlockchainReadLastNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AvswuBlockchainReadLastNotification() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_AvswuBlockchainReadLastNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadLastNotification(::grpc::ServerContext* context, ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::grpc::ServerAsyncResponseWriter< ::avswu::AvswuBlockchainReadLastNotificationReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AvswuBlockchainReadLastNotificationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AvswuBlockchainReadLastNotificationList() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_AvswuBlockchainReadLastNotificationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadLastNotificationList(::grpc::ServerContext* context, ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::grpc::ServerAsyncResponseWriter< ::avswu::AvswuBlockchainReadLastNotificationListReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AvswuBlockchainWriteCommitment<WithAsyncMethod_AvswuBlockchainReadCommitmentVector<WithAsyncMethod_AvswuBlockchainWriteNotification<WithAsyncMethod_AvswuBlockchainReadNotification<WithAsyncMethod_AvswuBlockchainReadLastNotification<WithAsyncMethod_AvswuBlockchainReadLastNotificationList<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AvswuBlockchainWriteCommitment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AvswuBlockchainWriteCommitment() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response) { return this->AvswuBlockchainWriteCommitment(context, request, response); }));}
    void SetMessageAllocatorFor_AvswuBlockchainWriteCommitment(
        ::grpc::MessageAllocator< ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AvswuBlockchainWriteCommitment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainWriteCommitment(
      ::grpc::CallbackServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AvswuBlockchainReadCommitmentVector : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AvswuBlockchainReadCommitmentVector() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response) { return this->AvswuBlockchainReadCommitmentVector(context, request, response); }));}
    void SetMessageAllocatorFor_AvswuBlockchainReadCommitmentVector(
        ::grpc::MessageAllocator< ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AvswuBlockchainReadCommitmentVector() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadCommitmentVector(
      ::grpc::CallbackServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AvswuBlockchainWriteNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AvswuBlockchainWriteNotification() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response) { return this->AvswuBlockchainWriteNotification(context, request, response); }));}
    void SetMessageAllocatorFor_AvswuBlockchainWriteNotification(
        ::grpc::MessageAllocator< ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AvswuBlockchainWriteNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainWriteNotification(
      ::grpc::CallbackServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AvswuBlockchainReadNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AvswuBlockchainReadNotification() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response) { return this->AvswuBlockchainReadNotification(context, request, response); }));}
    void SetMessageAllocatorFor_AvswuBlockchainReadNotification(
        ::grpc::MessageAllocator< ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AvswuBlockchainReadNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadNotification(
      ::grpc::CallbackServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AvswuBlockchainReadLastNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AvswuBlockchainReadLastNotification() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response) { return this->AvswuBlockchainReadLastNotification(context, request, response); }));}
    void SetMessageAllocatorFor_AvswuBlockchainReadLastNotification(
        ::grpc::MessageAllocator< ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AvswuBlockchainReadLastNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadLastNotification(
      ::grpc::CallbackServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AvswuBlockchainReadLastNotificationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AvswuBlockchainReadLastNotificationList() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response) { return this->AvswuBlockchainReadLastNotificationList(context, request, response); }));}
    void SetMessageAllocatorFor_AvswuBlockchainReadLastNotificationList(
        ::grpc::MessageAllocator< ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AvswuBlockchainReadLastNotificationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadLastNotificationList(
      ::grpc::CallbackServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AvswuBlockchainWriteCommitment<WithCallbackMethod_AvswuBlockchainReadCommitmentVector<WithCallbackMethod_AvswuBlockchainWriteNotification<WithCallbackMethod_AvswuBlockchainReadNotification<WithCallbackMethod_AvswuBlockchainReadLastNotification<WithCallbackMethod_AvswuBlockchainReadLastNotificationList<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AvswuBlockchainWriteCommitment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AvswuBlockchainWriteCommitment() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AvswuBlockchainWriteCommitment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AvswuBlockchainReadCommitmentVector : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AvswuBlockchainReadCommitmentVector() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AvswuBlockchainReadCommitmentVector() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AvswuBlockchainWriteNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AvswuBlockchainWriteNotification() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AvswuBlockchainWriteNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AvswuBlockchainReadNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AvswuBlockchainReadNotification() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_AvswuBlockchainReadNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AvswuBlockchainReadLastNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AvswuBlockchainReadLastNotification() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_AvswuBlockchainReadLastNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AvswuBlockchainReadLastNotificationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AvswuBlockchainReadLastNotificationList() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_AvswuBlockchainReadLastNotificationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AvswuBlockchainWriteCommitment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AvswuBlockchainWriteCommitment() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AvswuBlockchainWriteCommitment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainWriteCommitment(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AvswuBlockchainReadCommitmentVector : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AvswuBlockchainReadCommitmentVector() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AvswuBlockchainReadCommitmentVector() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadCommitmentVector(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AvswuBlockchainWriteNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AvswuBlockchainWriteNotification() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AvswuBlockchainWriteNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainWriteNotification(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AvswuBlockchainReadNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AvswuBlockchainReadNotification() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_AvswuBlockchainReadNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadNotification(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AvswuBlockchainReadLastNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AvswuBlockchainReadLastNotification() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_AvswuBlockchainReadLastNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadLastNotification(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AvswuBlockchainReadLastNotificationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AvswuBlockchainReadLastNotificationList() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_AvswuBlockchainReadLastNotificationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAvswuBlockchainReadLastNotificationList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AvswuBlockchainWriteCommitment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AvswuBlockchainWriteCommitment() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AvswuBlockchainWriteCommitment(context, request, response); }));
    }
    ~WithRawCallbackMethod_AvswuBlockchainWriteCommitment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainWriteCommitment(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AvswuBlockchainReadCommitmentVector : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AvswuBlockchainReadCommitmentVector() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AvswuBlockchainReadCommitmentVector(context, request, response); }));
    }
    ~WithRawCallbackMethod_AvswuBlockchainReadCommitmentVector() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadCommitmentVector(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AvswuBlockchainWriteNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AvswuBlockchainWriteNotification() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AvswuBlockchainWriteNotification(context, request, response); }));
    }
    ~WithRawCallbackMethod_AvswuBlockchainWriteNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainWriteNotification(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AvswuBlockchainReadNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AvswuBlockchainReadNotification() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AvswuBlockchainReadNotification(context, request, response); }));
    }
    ~WithRawCallbackMethod_AvswuBlockchainReadNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadNotification(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AvswuBlockchainReadLastNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AvswuBlockchainReadLastNotification() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AvswuBlockchainReadLastNotification(context, request, response); }));
    }
    ~WithRawCallbackMethod_AvswuBlockchainReadLastNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadLastNotification(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AvswuBlockchainReadLastNotificationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AvswuBlockchainReadLastNotificationList() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AvswuBlockchainReadLastNotificationList(context, request, response); }));
    }
    ~WithRawCallbackMethod_AvswuBlockchainReadLastNotificationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AvswuBlockchainReadLastNotificationList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AvswuBlockchainWriteCommitment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AvswuBlockchainWriteCommitment() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply>* streamer) {
                       return this->StreamedAvswuBlockchainWriteCommitment(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AvswuBlockchainWriteCommitment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AvswuBlockchainWriteCommitment(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteCommitmentRequest* /*request*/, ::avswu::AvswuBlockchainWriteCommitmentReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAvswuBlockchainWriteCommitment(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::avswu::AvswuBlockchainWriteCommitmentRequest,::avswu::AvswuBlockchainWriteCommitmentReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AvswuBlockchainReadCommitmentVector : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AvswuBlockchainReadCommitmentVector() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply>* streamer) {
                       return this->StreamedAvswuBlockchainReadCommitmentVector(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AvswuBlockchainReadCommitmentVector() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* /*request*/, ::avswu::AvswuBlockchainReadCommitmentVectorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAvswuBlockchainReadCommitmentVector(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::avswu::AvswuBlockchainReadCommitmentVectorRequest,::avswu::AvswuBlockchainReadCommitmentVectorReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AvswuBlockchainWriteNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AvswuBlockchainWriteNotification() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply>* streamer) {
                       return this->StreamedAvswuBlockchainWriteNotification(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AvswuBlockchainWriteNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AvswuBlockchainWriteNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainWriteNotificationRequest* /*request*/, ::avswu::AvswuBlockchainWriteNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAvswuBlockchainWriteNotification(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::avswu::AvswuBlockchainWriteNotificationRequest,::avswu::AvswuBlockchainWriteNotificationReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AvswuBlockchainReadNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AvswuBlockchainReadNotification() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply>* streamer) {
                       return this->StreamedAvswuBlockchainReadNotification(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AvswuBlockchainReadNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AvswuBlockchainReadNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAvswuBlockchainReadNotification(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::avswu::AvswuBlockchainReadNotificationRequest,::avswu::AvswuBlockchainReadNotificationReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AvswuBlockchainReadLastNotification : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AvswuBlockchainReadLastNotification() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply>* streamer) {
                       return this->StreamedAvswuBlockchainReadLastNotification(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AvswuBlockchainReadLastNotification() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AvswuBlockchainReadLastNotification(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAvswuBlockchainReadLastNotification(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::avswu::AvswuBlockchainReadLastNotificationRequest,::avswu::AvswuBlockchainReadLastNotificationReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AvswuBlockchainReadLastNotificationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AvswuBlockchainReadLastNotificationList() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply>* streamer) {
                       return this->StreamedAvswuBlockchainReadLastNotificationList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AvswuBlockchainReadLastNotificationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* /*context*/, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* /*request*/, ::avswu::AvswuBlockchainReadLastNotificationListReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAvswuBlockchainReadLastNotificationList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::avswu::AvswuBlockchainReadLastNotificationListRequest,::avswu::AvswuBlockchainReadLastNotificationListReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AvswuBlockchainWriteCommitment<WithStreamedUnaryMethod_AvswuBlockchainReadCommitmentVector<WithStreamedUnaryMethod_AvswuBlockchainWriteNotification<WithStreamedUnaryMethod_AvswuBlockchainReadNotification<WithStreamedUnaryMethod_AvswuBlockchainReadLastNotification<WithStreamedUnaryMethod_AvswuBlockchainReadLastNotificationList<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AvswuBlockchainWriteCommitment<WithStreamedUnaryMethod_AvswuBlockchainReadCommitmentVector<WithStreamedUnaryMethod_AvswuBlockchainWriteNotification<WithStreamedUnaryMethod_AvswuBlockchainReadNotification<WithStreamedUnaryMethod_AvswuBlockchainReadLastNotification<WithStreamedUnaryMethod_AvswuBlockchainReadLastNotificationList<Service > > > > > > StreamedService;
};

}  // namespace avswu


#endif  // GRPC_veins_5favswu_2eproto__INCLUDED
