// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: veins_avswu.proto

#include "veins_avswu.pb.h"
#include "veins_avswu.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace avswu {

static const char* Avswu_method_names[] = {
  "/avswu.Avswu/AvswuBlockchainWriteCommitment",
  "/avswu.Avswu/AvswuBlockchainReadCommitmentVector",
  "/avswu.Avswu/AvswuBlockchainWriteNotification",
  "/avswu.Avswu/AvswuBlockchainReadNotification",
  "/avswu.Avswu/AvswuBlockchainReadLastNotification",
  "/avswu.Avswu/AvswuBlockchainReadLastNotificationList",
};

std::unique_ptr< Avswu::Stub> Avswu::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Avswu::Stub> stub(new Avswu::Stub(channel, options));
  return stub;
}

Avswu::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AvswuBlockchainWriteCommitment_(Avswu_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AvswuBlockchainReadCommitmentVector_(Avswu_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AvswuBlockchainWriteNotification_(Avswu_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AvswuBlockchainReadNotification_(Avswu_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AvswuBlockchainReadLastNotification_(Avswu_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AvswuBlockchainReadLastNotificationList_(Avswu_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Avswu::Stub::AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::avswu::AvswuBlockchainWriteCommitmentReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AvswuBlockchainWriteCommitment_, context, request, response);
}

void Avswu::Stub::async::AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainWriteCommitment_, context, request, response, std::move(f));
}

void Avswu::Stub::async::AvswuBlockchainWriteCommitment(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainWriteCommitment_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>* Avswu::Stub::PrepareAsyncAvswuBlockchainWriteCommitmentRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::avswu::AvswuBlockchainWriteCommitmentReply, ::avswu::AvswuBlockchainWriteCommitmentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AvswuBlockchainWriteCommitment_, context, request);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteCommitmentReply>* Avswu::Stub::AsyncAvswuBlockchainWriteCommitmentRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAvswuBlockchainWriteCommitmentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Avswu::Stub::AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AvswuBlockchainReadCommitmentVector_, context, request, response);
}

void Avswu::Stub::async::AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadCommitmentVector_, context, request, response, std::move(f));
}

void Avswu::Stub::async::AvswuBlockchainReadCommitmentVector(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadCommitmentVector_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* Avswu::Stub::PrepareAsyncAvswuBlockchainReadCommitmentVectorRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::avswu::AvswuBlockchainReadCommitmentVectorReply, ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AvswuBlockchainReadCommitmentVector_, context, request);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadCommitmentVectorReply>* Avswu::Stub::AsyncAvswuBlockchainReadCommitmentVectorRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAvswuBlockchainReadCommitmentVectorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Avswu::Stub::AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::avswu::AvswuBlockchainWriteNotificationReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AvswuBlockchainWriteNotification_, context, request, response);
}

void Avswu::Stub::async::AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainWriteNotification_, context, request, response, std::move(f));
}

void Avswu::Stub::async::AvswuBlockchainWriteNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainWriteNotification_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>* Avswu::Stub::PrepareAsyncAvswuBlockchainWriteNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::avswu::AvswuBlockchainWriteNotificationReply, ::avswu::AvswuBlockchainWriteNotificationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AvswuBlockchainWriteNotification_, context, request);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainWriteNotificationReply>* Avswu::Stub::AsyncAvswuBlockchainWriteNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAvswuBlockchainWriteNotificationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Avswu::Stub::AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::avswu::AvswuBlockchainReadNotificationReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AvswuBlockchainReadNotification_, context, request, response);
}

void Avswu::Stub::async::AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadNotification_, context, request, response, std::move(f));
}

void Avswu::Stub::async::AvswuBlockchainReadNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadNotification_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>* Avswu::Stub::PrepareAsyncAvswuBlockchainReadNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::avswu::AvswuBlockchainReadNotificationReply, ::avswu::AvswuBlockchainReadNotificationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AvswuBlockchainReadNotification_, context, request);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadNotificationReply>* Avswu::Stub::AsyncAvswuBlockchainReadNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAvswuBlockchainReadNotificationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Avswu::Stub::AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::avswu::AvswuBlockchainReadLastNotificationReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AvswuBlockchainReadLastNotification_, context, request, response);
}

void Avswu::Stub::async::AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadLastNotification_, context, request, response, std::move(f));
}

void Avswu::Stub::async::AvswuBlockchainReadLastNotification(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadLastNotification_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>* Avswu::Stub::PrepareAsyncAvswuBlockchainReadLastNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::avswu::AvswuBlockchainReadLastNotificationReply, ::avswu::AvswuBlockchainReadLastNotificationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AvswuBlockchainReadLastNotification_, context, request);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationReply>* Avswu::Stub::AsyncAvswuBlockchainReadLastNotificationRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAvswuBlockchainReadLastNotificationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Avswu::Stub::AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AvswuBlockchainReadLastNotificationList_, context, request, response);
}

void Avswu::Stub::async::AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadLastNotificationList_, context, request, response, std::move(f));
}

void Avswu::Stub::async::AvswuBlockchainReadLastNotificationList(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AvswuBlockchainReadLastNotificationList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>* Avswu::Stub::PrepareAsyncAvswuBlockchainReadLastNotificationListRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::avswu::AvswuBlockchainReadLastNotificationListReply, ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AvswuBlockchainReadLastNotificationList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::avswu::AvswuBlockchainReadLastNotificationListReply>* Avswu::Stub::AsyncAvswuBlockchainReadLastNotificationListRaw(::grpc::ClientContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAvswuBlockchainReadLastNotificationListRaw(context, request, cq);
  result->StartCall();
  return result;
}

Avswu::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Avswu_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Avswu::Service, ::avswu::AvswuBlockchainWriteCommitmentRequest, ::avswu::AvswuBlockchainWriteCommitmentReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Avswu::Service* service,
             ::grpc::ServerContext* ctx,
             const ::avswu::AvswuBlockchainWriteCommitmentRequest* req,
             ::avswu::AvswuBlockchainWriteCommitmentReply* resp) {
               return service->AvswuBlockchainWriteCommitment(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Avswu_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Avswu::Service, ::avswu::AvswuBlockchainReadCommitmentVectorRequest, ::avswu::AvswuBlockchainReadCommitmentVectorReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Avswu::Service* service,
             ::grpc::ServerContext* ctx,
             const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* req,
             ::avswu::AvswuBlockchainReadCommitmentVectorReply* resp) {
               return service->AvswuBlockchainReadCommitmentVector(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Avswu_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Avswu::Service, ::avswu::AvswuBlockchainWriteNotificationRequest, ::avswu::AvswuBlockchainWriteNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Avswu::Service* service,
             ::grpc::ServerContext* ctx,
             const ::avswu::AvswuBlockchainWriteNotificationRequest* req,
             ::avswu::AvswuBlockchainWriteNotificationReply* resp) {
               return service->AvswuBlockchainWriteNotification(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Avswu_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Avswu::Service, ::avswu::AvswuBlockchainReadNotificationRequest, ::avswu::AvswuBlockchainReadNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Avswu::Service* service,
             ::grpc::ServerContext* ctx,
             const ::avswu::AvswuBlockchainReadNotificationRequest* req,
             ::avswu::AvswuBlockchainReadNotificationReply* resp) {
               return service->AvswuBlockchainReadNotification(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Avswu_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Avswu::Service, ::avswu::AvswuBlockchainReadLastNotificationRequest, ::avswu::AvswuBlockchainReadLastNotificationReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Avswu::Service* service,
             ::grpc::ServerContext* ctx,
             const ::avswu::AvswuBlockchainReadLastNotificationRequest* req,
             ::avswu::AvswuBlockchainReadLastNotificationReply* resp) {
               return service->AvswuBlockchainReadLastNotification(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Avswu_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Avswu::Service, ::avswu::AvswuBlockchainReadLastNotificationListRequest, ::avswu::AvswuBlockchainReadLastNotificationListReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Avswu::Service* service,
             ::grpc::ServerContext* ctx,
             const ::avswu::AvswuBlockchainReadLastNotificationListRequest* req,
             ::avswu::AvswuBlockchainReadLastNotificationListReply* resp) {
               return service->AvswuBlockchainReadLastNotificationList(ctx, req, resp);
             }, this)));
}

Avswu::Service::~Service() {
}

::grpc::Status Avswu::Service::AvswuBlockchainWriteCommitment(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainWriteCommitmentRequest* request, ::avswu::AvswuBlockchainWriteCommitmentReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Avswu::Service::AvswuBlockchainReadCommitmentVector(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadCommitmentVectorRequest* request, ::avswu::AvswuBlockchainReadCommitmentVectorReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Avswu::Service::AvswuBlockchainWriteNotification(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainWriteNotificationRequest* request, ::avswu::AvswuBlockchainWriteNotificationReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Avswu::Service::AvswuBlockchainReadNotification(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadNotificationRequest* request, ::avswu::AvswuBlockchainReadNotificationReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Avswu::Service::AvswuBlockchainReadLastNotification(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadLastNotificationRequest* request, ::avswu::AvswuBlockchainReadLastNotificationReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Avswu::Service::AvswuBlockchainReadLastNotificationList(::grpc::ServerContext* context, const ::avswu::AvswuBlockchainReadLastNotificationListRequest* request, ::avswu::AvswuBlockchainReadLastNotificationListReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace avswu

