//
// Generated file, do not edit! Created by nedtool 5.7 from veins_avswu/AvswuAV11pMessage.msg.
//

#ifndef __VEINS_AVSWUAV11PMESSAGE_M_H
#define __VEINS_AVSWUAV11PMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef thread_API
#  if defined(thread_EXPORT)
#    define thread_API  OPP_DLLEXPORT
#  elif defined(thread_IMPORT)
#    define thread_API  OPP_DLLIMPORT
#  else
#    define thread_API
#  endif
#endif


namespace veins {

class AvswuAV11pMessage;
} // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>veins_avswu/AvswuAV11pMessage.msg:29</tt> by nedtool.
 * <pre>
 * packet AvswuAV11pMessage extends BaseFrame1609_4
 * {
 *     string demoData;
 *     LAddress::L2Type senderAddress = -1;
 *     int serial = 0;
 *     LAddress::L2Type senderId = -1;
 *     string senderType;
 *     string payload;
 * }
 * </pre>
 */
class thread_API AvswuAV11pMessage : public ::veins::BaseFrame1609_4
{
  protected:
    omnetpp::opp_string demoData;
    LAddress::L2Type senderAddress = -1;
    int serial = 0;
    LAddress::L2Type senderId = -1;
    omnetpp::opp_string senderType;
    omnetpp::opp_string payload;

  private:
    void copy(const AvswuAV11pMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AvswuAV11pMessage&);

  public:
    AvswuAV11pMessage(const char *name=nullptr, short kind=0);
    AvswuAV11pMessage(const AvswuAV11pMessage& other);
    virtual ~AvswuAV11pMessage();
    AvswuAV11pMessage& operator=(const AvswuAV11pMessage& other);
    virtual AvswuAV11pMessage *dup() const override {return new AvswuAV11pMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDemoData() const;
    virtual void setDemoData(const char * demoData);
    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<AvswuAV11pMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
    virtual int getSerial() const;
    virtual void setSerial(int serial);
    virtual const LAddress::L2Type& getSenderId() const;
    virtual LAddress::L2Type& getSenderIdForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<AvswuAV11pMessage*>(this)->getSenderId());}
    virtual void setSenderId(const LAddress::L2Type& senderId);
    virtual const char * getSenderType() const;
    virtual void setSenderType(const char * senderType);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AvswuAV11pMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AvswuAV11pMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_AVSWUAV11PMESSAGE_M_H

